### ISSUE TITLE
Forecast Summary Undefined Issue

### ISSUE THREAD

**Issue by josephistired** [hamedpa/weathers-watch#10]
Hello, I noticed that the minimum temperature for the current day is showing up as undefined in the forecast summary. I am not sure why this is happening and would appreciate any insights or suggestions for how to fix it. Thank you!

![image](https://user-images.githubusercontent.com/65987360/233759055-3b6848b5-2ee9-44d9-8f8e-070eb390945d.png)

**Comment by pariazar** [comment]
Hello, Minimum or maximum temperature data is provided by a third-party service, and I have no control over this data. However, an alternative solution would be to utilize another API such as [OpenWeatherMap](https://openweathermap.org/api/one-call-3) API. This particular API offers access to weather data from around the world, which includes temperature, humidity, wind speed, and much more.

**Comment by josephistired** [comment]
Thank you for letting me know, and I completely understand! I'll look into using OpenWeatherMap API for my project!
